export const TIMES = [
    {id: "u1", name: "1시간"},
    {id: "u2", name: "2시간"},
    {id: "u3", name: "3시간"},
    {id: "u4", name: "4시간"},
    {id: "u5", name: "5시간"},
    {id: "v6", name: "6시간"},
    {id: "v9", name: "9시간"},
    {id: "v12", name: "12시간"},
    {id: "v15", name: "15시간"},
    {id: "v18", name: "18시간"},
    {id: "v21", name: "21시간"},
    {id: "v24", name: "24시간"},
    {id: "v36", name: "36시간"},
    {id: "v48", name: "48시간"},
    {id: "d3", name: "3일"},
    {id: "d4", name: "4일"},
    {id: "d5", name: "5일"},
    {id: "d6", name: "6일"},
    {id: "d7", name: "7일"},
    {id: "d8", name: "8일"},
    {id: "d9", name: "9일"},
]